CREATE TABLE IF NOT EXISTS nhl_players (
    id INTEGER NOT NULL PRIMARY KEY,
    full_name VARCHAR(40) NOT NULL,
    link VARCHAR(40) NOT NULL,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    primary_number VARCHAR(3) NOT NULL,
    birth_date VARCHAR(40) NOT NULL,
    current_age INTEGER NOT NULL,
    birth_city VARCHAR(40) NOT NULL,
    birth_state_province VARCHAR(40),
    birth_country VARCHAR(40) NOT NULL,
    nationality VARCHAR(40) NOT NULL,
    height VARCHAR(40) NOT NULL,
    player_weight INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    alternate_captain BOOLEAN NOT NULL,
    captain BOOLEAN NOT NULL,
    rookie BOOLEAN NOT NULL,
    shoots_catches VARCHAR(2) NOT NULL,
    roster_status VARCHAR(2) NOT NULL,
    current_team VARCHAR(40) NOT NULL,
    primary_position VARCHAR(40) NOT NULL
)