CREATE TABLE IF NOT EXISTS nhl_games (
    playerid_gameid VARCHAR(40) NOT NULL PRIMARY KEY,
    player_id INTEGER NOT NULL,
    game_id VARCHAR(40) NOT NULL,
    full_name VARCHAR(40) NOT NULL,
    team_id INTEGER NOT NULL,
    team_name VARCHAR(40) NOT NULL,
    primary_number VARCHAR(3) NOT NULL,
    primary_position VARCHAR(40) NOT NULL,
    assists INTEGER DEFAULT 0,
    goals INTEGER DEFAULT 0,
    shots INTEGER DEFAULT 0,
    hits INTEGER DEFAULT 0,
    power_play_goals INTEGER DEFAULT 0,
    power_play_assists INTEGER DEFAULT 0,
    penalty_minutes INTEGER DEFAULT 0,
    face_off_wins INTEGER DEFAULT 0,
    face_off_taken INTEGER DEFAULT 0,
    takeaways INTEGER DEFAULT 0,
    giveaways INTEGER DEFAULT 0,
    short_handed_goals INTEGER DEFAULT 0,
    blocked INTEGER DEFAULT 0,
    plus_minus INTEGER DEFAULT 0,
    opponent_team VARCHAR(40)
)
